name: Run JavaScript Code

on: [push]

jobs:
  run_js_code:
    name: Run JavaScript Code Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Run JavaScript file
        run: node batch10.js
